[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 8888
  publish = "dist"
  autoLaunch = true
<<<<<<< HEAD
  framework = "#custom"
=======
  framework = "#custom"

# Add the plugin configuration for Takeshape
[[plugins]]
package = "@takeshape/netlify-plugin-takeshape"

[plugins.inputs]
  query = """
  query {
    projects: getProjectList {
      id
      name
    }
  }
  """
>>>>>>> b597b98 (Update project files and sync with GitHub)
