# Global settings for the build & deploy process
[build]
command = "yarn build"
publish = "dist"

  [build.environment]
    VITE_API_URL = "https://www.protaxadvisors.tax"
    VITE_ENV = "production"
    OPENAI_API_KEY = "your-production-key"
    NODE_ENV = "production"

# Local development environment using Netlify Dev
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173  # Match Vite's default dev server port

# Redirects for Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers for API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"