import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Award, TrendingUp, BookOpen, CheckCircle } from 'lucide-react';
import { Card } from '../ui/Card';
import { ProgressChart } from './dashboard/ProgressChart';
export function ProgressTracking() {
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "flex justify-between items-center", children: _jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "Progress Tracking" }) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6", children: [_jsx(Card, { icon: Award, title: "Total Points", value: "450", description: "+50 this week" }), _jsx(Card, { icon: BookOpen, title: "Completed Exercises", value: "12", description: "75% completion rate" }), _jsx(Card, { icon: TrendingUp, title: "Current Streak", value: "5 days", description: "Personal best: 7 days" }), _jsx(Card, { icon: CheckCircle, title: "Achievements", value: "8/15", description: "3 new this month" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h2", { className: "text-lg font-medium text-gray-900 mb-4", children: "Learning Progress" }), _jsx(ProgressChart, {})] }), _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h2", { className: "text-lg font-medium text-gray-900 mb-4", children: "Recent Achievements" }), _jsx("div", { className: "space-y-4", children: [
                                    { name: 'Tax Master', description: 'Complete 5 tax calculation exercises', date: '2 days ago' },
                                    { name: 'Quick Learner', description: 'Finish 3 exercises in one day', date: '5 days ago' },
                                    { name: 'Perfect Score', description: 'Score 100% on an advanced exercise', date: '1 week ago' }
                                ].map((achievement, index) => (_jsxs("div", { className: "flex items-start space-x-3", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx("div", { className: "h-8 w-8 rounded-full bg-blue-100 flex items-center justify-center", children: _jsx(Award, { className: "h-4 w-4 text-blue-600" }) }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: achievement.name }), _jsx("p", { className: "text-sm text-gray-500", children: achievement.description }), _jsx("p", { className: "text-xs text-gray-400 mt-1", children: achievement.date })] })] }, index))) })] })] })] }));
}
