import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Mail, Linkedin, ExternalLink } from 'lucide-react';
import { Button } from '../ui/Button';
export function TeamMember({ id, name, role, description, image, email, linkedin, website, onEdit, onDelete, isAdmin }) {
    const FALLBACK_IMAGE = 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=facearea&facepad=2&w=300&h=300&q=80';
    return (_jsxs("div", { className: "bg-white rounded-xl shadow-lg overflow-hidden transform transition-all duration-300 hover:-translate-y-1 hover:shadow-xl", children: [_jsx("div", { className: "aspect-w-4 aspect-h-3", children: _jsx("img", { src: image, alt: `${name} - ${role}`, className: "w-full h-64 object-cover", loading: "lazy", onError: (e) => {
                        const target = e.target;
                        target.src = FALLBACK_IMAGE;
                    } }) }), _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "text-xl font-semibold text-gray-900", children: name }), _jsx("p", { className: "text-blue-600 font-medium mt-1", children: role }), _jsx("p", { className: "mt-3 text-gray-600 text-sm line-clamp-4", children: description }), _jsxs("div", { className: "mt-4 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [email && (_jsx(Button, { variant: "outline", size: "sm", icon: Mail, onClick: () => window.location.href = `mailto:${email}`, className: "hover:text-blue-600" })), linkedin && (_jsx(Button, { variant: "outline", size: "sm", icon: Linkedin, onClick: () => window.open(linkedin, '_blank'), className: "hover:text-blue-600" })), website && (_jsx(Button, { variant: "outline", size: "sm", icon: ExternalLink, onClick: () => window.open(website, '_blank'), className: "hover:text-blue-600" }))] }), isAdmin && (_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Button, { variant: "outline", size: "sm", onClick: () => onEdit?.({ id, name, role, description, image, email, linkedin, website }), children: "Edit" }), _jsx(Button, { variant: "outline", size: "sm", className: "text-red-600 hover:text-red-700", onClick: () => onDelete?.(id), children: "Delete" })] }))] })] })] }));
}
