import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { TrendingUp, PlayCircle, Users, BookOpen } from 'lucide-react';
export function InvestorDashboard() {
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4", children: [_jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsx("div", { className: "p-5", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(TrendingUp, { className: "h-6 w-6 text-blue-600" }) }), _jsx("div", { className: "ml-5 w-0 flex-1", children: _jsxs("dl", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 truncate", children: "Investment Performance" }), _jsx("dd", { className: "text-lg font-medium text-gray-900", children: "+12.5%" })] }) })] }) }) }), _jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsx("div", { className: "p-5", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(PlayCircle, { className: "h-6 w-6 text-blue-600" }) }), _jsx("div", { className: "ml-5 w-0 flex-1", children: _jsxs("dl", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 truncate", children: "Video Resources" }), _jsx("dd", { className: "text-lg font-medium text-gray-900", children: "24" })] }) })] }) }) }), _jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsx("div", { className: "p-5", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(Users, { className: "h-6 w-6 text-blue-600" }) }), _jsx("div", { className: "ml-5 w-0 flex-1", children: _jsxs("dl", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 truncate", children: "Network Members" }), _jsx("dd", { className: "text-lg font-medium text-gray-900", children: "156" })] }) })] }) }) }), _jsx("div", { className: "bg-white overflow-hidden shadow rounded-lg", children: _jsx("div", { className: "p-5", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(BookOpen, { className: "h-6 w-6 text-blue-600" }) }), _jsx("div", { className: "ml-5 w-0 flex-1", children: _jsxs("dl", { children: [_jsx("dt", { className: "text-sm font-medium text-gray-500 truncate", children: "Resources" }), _jsx("dd", { className: "text-lg font-medium text-gray-900", children: "42" })] }) })] }) }) })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-8", children: [_jsx("div", { className: "bg-white shadow rounded-lg", children: _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "text-lg font-medium text-gray-900 mb-4", children: "Latest Video Content" }), _jsx("div", { className: "space-y-4", children: [
                                        {
                                            title: 'Q1 2024 Market Analysis',
                                            duration: '45 min',
                                            thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=300'
                                        },
                                        {
                                            title: 'Investment Strategies Workshop',
                                            duration: '60 min',
                                            thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=300'
                                        }
                                    ].map((video, index) => (_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("img", { src: video.thumbnail, alt: video.title, className: "h-20 w-32 object-cover rounded" }), _jsxs("div", { children: [_jsx("h4", { className: "text-sm font-medium text-gray-900", children: video.title }), _jsx("p", { className: "text-sm text-gray-500", children: video.duration })] })] }, index))) })] }) }), _jsx("div", { className: "bg-white shadow rounded-lg", children: _jsxs("div", { className: "p-6", children: [_jsx("h3", { className: "text-lg font-medium text-gray-900 mb-4", children: "Professional Network" }), _jsx("div", { className: "space-y-4", children: [
                                        {
                                            name: 'Sarah Johnson',
                                            role: 'Financial Advisor',
                                            avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100'
                                        },
                                        {
                                            name: 'Michael Chen',
                                            role: 'Investment Analyst',
                                            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100'
                                        }
                                    ].map((member, index) => (_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("img", { src: member.avatar, alt: member.name, className: "h-10 w-10 rounded-full" }), _jsxs("div", { children: [_jsx("h4", { className: "text-sm font-medium text-gray-900", children: member.name }), _jsx("p", { className: "text-sm text-gray-500", children: member.role })] })] }, index))) })] }) })] })] }));
}
